CREATE DATABASE `U_17100183`;
USE `U_17100183`;
CREATE TABLE USUARIOS(
ID int NOT NULL AUTO_INCREMENT,
NOMBRE VARCHAR(50),
APELLIDO_P VARCHAR(20),
APELLIDO_M VARCHAR(20),
PRIMARY KEY (ID));

INSERT INTO USUARIOS VALUES(DEFAULT,'Jose Luis','Anguiano','Lopez');
INSERT INTO USUARIOS VALUES(DEFAULT,'Jaime Sebastian','Tenorio','Rios');
INSERT INTO USUARIOS VALUES(DEFAULT,'Jesus Bulmaro','Hernandez','Garcia');
INSERT INTO USUARIOS VALUES(DEFAULT,'Jaime Andres','Cortina','Rangel');
INSERT INTO USUARIOS VALUES(DEFAULT,'Francisco Fernando','Gonzalez','Rodriguez');
